location ~ (^|/)\. {
  return 403;
}

# Protect Drupal-specific files and directories from prying eyes.
location ~ \.(engine|inc|install|module|profile|theme|twig|tpl(\.php)?|yml)$ {
  deny all;
  return 404;
}

# Protect non-Drupal files and directories from prying eyes.
location ~ \.(log|make|po|sh|.*sql|.*sql\.gz|xtmpl)(~|\.sw[op]|\.bak|\.orig|\.save)?$|^\/#.*#$|\.php(~|\.sw[op]|\.bak|\.orig|\.save)$ {
  deny all;
  return 404;
}

# Protect Drupal-adjacent files and directories from prying eyes
# Drupal defaults to provide protection against access to these.
location ~ (composer\.(json|lock)|web\.config|yarn\.lock|package(-lock)?\.json)$ {
  deny all;
  return 404;
}

# Protect miscellaneous files and directories from prying eyes.
# Drupal defaults to provide protection against access to these.
location ~ ^\/(\.(?!well-known).*|Entries.*|Repository|Root|Tag|Template)$ {
  deny all;
  return 404;
}
