# Cross-Origin-Opener-Policy prevents other origins from gaining a reference to this window.
# same-origin-allow-popups is used to preserve OAuth and payment popup flows.
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cross-Origin-Opener-Policy
add_header Cross-Origin-Opener-Policy "same-origin-allow-popups" always;
